import { RiDownload2Line, RiUserAddLine } from "@remixicon/react";

export const TAB_OPTIONS = [
	{ icon: RiUserAddLine, label: "Referral History", value: "referral" },
	{ icon: RiDownload2Line, label: "Withdrawal History", value: "withdrawal" },
];

export const NIGERIAN_BANKS = [
	{ name: "Access Bank", code: "044" },
	{ name: "Access Bank (Diamond)", code: "063" },
	{ name: "Citibank", code: "023" },
	{ name: "Dynamic Standard Bank", code: "" },
	{ name: "Ecobank Nigeria", code: "050" },
	{ name: "Fidelity Bank Nigeria", code: "070" },
	{ name: "First Bank of Nigeria", code: "011" },
	{ name: "First City Monument Bank", code: "214" },
	{ name: "Guaranty Trust Bank", code: "058" },
	{ name: "Heritage Bank Plc", code: "030" },
	{ name: "Jaiz Bank", code: "301" },
	{ name: "Keystone Bank Limited", code: "082" },
	{ name: "Providus Bank Plc", code: "101" },
	{ name: "Polaris Bank", code: "076" },
	{ name: "Stanbic IBTC Bank Nigeria Limited", code: "221" },
	{ name: "Standard Chartered Bank", code: "068" },
	{ name: "Sterling Bank", code: "232" },
	{ name: "Suntrust Bank Nigeria Limited", code: "100" },
	{ name: "Union Bank of Nigeria", code: "032" },
	{ name: "United Bank for Africa", code: "033" },
	{ name: "Unity Bank Plc", code: "215" },
	{ name: "Wema Bank", code: "035" },
	{ name: "Zenith Bank", code: "057" },
	{ name: "Titan Bank", code: "102" },
	{ name: "VFD Microfinance Bank Limited", code: "566" },
	{ name: "Rubies MFB", code: "125" },
	{ name: "Rand Merchant Bank", code: "502" },
	{ name: "Paystack-Titan", code: "100039" },
	{ name: "OPay Digital Services Limited (OPay)", code: "999992" },
	{ name: "Optimus Bank Limited", code: "107" },
	{ name: "Paga", code: "100002" },
	{ name: "PalmPay", code: "999991" },
	{ name: "Parallex Bank", code: "104" },
	{ name: "Moniepoint MFB", code: "50515" },
	{ name: "MTN Momo PSB", code: "120003" },
	{ name: "Lotus Bank", code: "303" },
	{ name: "Kuda Bank", code: "50211" },
	{ name: "Globus Bank", code: "00103" },
	{ name: "Taj Bank", code: "302" },
	{ name: "Eyowo", code: "50126" },
	{ name: "Fairmoney Microfinance Bank", code: "51318" },
	{ name: "Carbon", code: "565" },
];
