export const NIGERIAN_BANKS = [
	{ name: "First Bank", code: "" },
	{ name: "Guaranty Trust Bank (GTBank)", code: "" },
	{ name: "Access Bank", code: "" },
	{ name: "United Bank for Africa", code: "" },
	{ name: "Zenith Bank", code: "" },
	{ name: "FCMB", code: "" },
	{ name: "Sterling Bank", code: "" },
	{ name: "Wema Bank", code: "" },
	{ name: "Union Bank", code: "" },
	{ name: "Fidelity Bank", code: "" },
	{ name: "Ecobank Nigeria", code: "" },
	{ name: "Heritage Bank", code: "" },
	{ name: "Kuda Bank", code: "" },
	{ name: "Carbon", code: "" },
	{ name: "Opay", code: "" },
	{ name: "Rubies Bank", code: "" },
	{ name: "PalmPay", code: "" },
	{ name: "Titans Bank", code: "" },
	{ name: "VFD Microfinance Bank", code: "" },
	{ name: "Moniepoint", code: "" },
	{ name: "Eyowo", code: "" },
	{ name: "Down Bank", code: "" },
	{ name: "PayTM", code: "" },
	{ name: "Prosperity Bank", code: "" },
	{ name: "Citibank Nigeria", code: "" },
	{ name: "Standard Chartered Bank Nigeria", code: "" },
	{ name: "Jaiz Bank", code: "" },
	{ name: "Lotus Bank", code: "" },
];
